# -*- coding: utf-8 -*-
"""Data Profiling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1baU9qNP85TqI3roOwmNoxTpZVDT_DgWm
"""

!pip install -U ydata-profiling

import pandas as pd
from ydata_profiling import ProfileReport  # Se usa ydata_profiling en lugar de pandas_profiling

url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)

profile = ProfileReport(df, title="Informe del Titanic", explorative=True)

profile.to_notebook_iframe()

"""SWEETVIZ

"""

!pip install sweetviz

import pandas as pd
import sweetviz as sv

url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)

report = sv.analyze(df)

report.show_html("sweetviz_report.html")  # Se genera un archivo HTML

"""AUTOVIZ"""

!pip install -U autoviz

import pandas as pd
from autoviz.AutoViz_Class import AutoViz_Class

AV = AutoViz_Class()

url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)

AV.AutoViz(filename="", dfte=df, depVar="", verbose=2, chart_format="svg")