version: '3.8'

services:
  namenode:
    build:
      context: .
      dockerfile: Dockerfile.namenode
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
      - "5556:5556"
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - namenode_data:/hadoop/dfs/name
    networks:
      - hadoop-net

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    depends_on:
      - namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - datanode1_data:/hadoop/dfs/data
    networks:
      - hadoop-net

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    depends_on:
      - namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - datanode2_data:/hadoop/dfs/data
    networks:
      - hadoop-net

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    ports:
      - "8088:8088"
    environment:
      - SERVICE_PRECONDITION=namenode:9000 datanode1:9864 datanode2:9864
    networks:
      - hadoop-net

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    environment:
      - SERVICE_PRECONDITION=resourcemanager:8088
    networks:
      - hadoop-net

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hadoop-net

  hive-metastore-db:
    image: postgres:12
    container_name: hive-metastore-db
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    networks:
      - hadoop-net

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    depends_on:
      - hive-metastore-db
      - namenode
    environment:
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore-db/metastore
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName=hive
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword=hive
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "10000:10000"
    networks:
      - hadoop-net

  sqoop:
    image: dvoros/sqoop
    container_name: sqoop
    tty: true
    environment:
      - HADOOP_COMMON_HOME=/usr/local/hadoop
    networks:
      - hadoop-net
    volumes:
      - ./mysql-connector-j-9.6.0.jar:/usr/local/sqoop/lib/mysql-connector-j-9.6.0.jar
    depends_on:
      - namenode
      - mysql

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - hadoop-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - hadoop-net

networks:
  hadoop-net:
    driver: bridge

volumes:
  namenode_data:
  datanode1_data:
  datanode2_data:
  hive_metastore_db:
  mysql_data: