# -*- coding: utf-8 -*-
"""PolarsPandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hIWU53DVwI6uRcDleElEHC0uXsR1FY1T
"""

import pandas as pd
import polars as pl
import numpy as np

data = {"col1": np.random.randint(0, 100, 1_000_000),
        "col2": np.random.randint(0, 100, 1_000_000)}

df_pandas = pd.DataFrame(data)
df_polars = pl.DataFrame(data)

import time

# Pandas
start = time.time()
result_pandas = df_pandas["col1"].sum()
print(f"Pandas: {time.time() - start:.4f} segundos")

# Polars
start = time.time()
result_polars = df_polars["col1"].sum()
print(f"Polars: {time.time() - start:.4f} segundos")

import pandas as pd
import polars as pl
import numpy as np

data = {"col1": np.random.randint(0, 100, 10_000_000),
        "col2": np.random.randint(0, 100, 10_000_000)}

df_pandas = pd.DataFrame(data)
df_polars = pl.DataFrame(data)

import pandas as pd
import numpy as np
import time

np.random.seed(0)
data_pandas = {
    "col1": np.random.randint(0, 100, 10_000_000),
    "col2": np.random.randint(0, 100, 10_000_000)
}
df_pandas = pd.DataFrame(data_pandas)

start_time = time.time()
result_pandas = df_pandas[df_pandas["col1"] > 50].groupby("col1")["col2"].mean()
pandas_duration = time.time() - start_time

print(f"Tiempo de ejecución con Pandas: {pandas_duration:.4f} segundos")
print(result_pandas.head())

import polars as pl

data_polars = {
    "col1": np.random.randint(0, 100, 10_000_000),
    "col2": np.random.randint(0, 100, 10_000_000)
}
df_polars = pl.DataFrame(data_polars)

start_time = time.time()
result_polars = (
    df_polars
    .filter(pl.col("col1") > 50)
    .group_by("col1")
    .agg(pl.col("col2").mean().alias("mean_col2"))
)
polars_duration = time.time() - start_time

print(f"Tiempo de ejecución con Polars: {polars_duration:.4f} segundos")
print(result_polars.head())