# -*- coding: utf-8 -*-
"""PySparkMapReduce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Th19fu-Lz9ps8yAj2zFSSx93w9oiE0WV
"""

!pip install pyspark

from pyspark.sql import SparkSession
from pyspark.sql.functions import explode, split, col

spark = SparkSession.builder \
    .appName("PySpark_MapReduce") \
    .getOrCreate()

data = [
    ("hola mundo hola"),
    ("hola pyspark pyspark pyspark"),
    ("big data con pyspark"),
    ("map reduce con pyspark"),
    ("big data hadoop spark")
]

rdd = spark.sparkContext.parallelize(data)
df = rdd.map(lambda x: (x, )).toDF(["sentence"])

# Map
df_words = df.select(explode(split(col("sentence"), " ")).alias("word"))
# Reduce
word_counts = df_words.groupBy("word").count()

word_counts.show()

!pip install pyspark

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, split, explode, sha2, concat_ws, avg, sum, count, min, max
import random

spark = SparkSession.builder.appName("PySpark_Demo").getOrCreate()

print("\n 1. MAP REDUCE - Conteo de Palabras")
data = [("Hola mundo"), ("Hola Spark"), ("PySpark es potente"), ("Hola mundo PySpark")]
df = spark.createDataFrame([(d,) for d in data], ["sentence"])
words = df.select(explode(split(col("sentence"), " ")).alias("word"))
word_counts = words.groupBy("word").count()
word_counts.show()

print("\n 2. SUMA DE VERIFICACIÓN")
data = [("Hola mundo"), ("Hola Spark"), ("PySpark es potente")]
df = spark.createDataFrame([(d,) for d in data], ["sentence"])
checksum_df = df.withColumn("checksum", sha2(col("sentence"), 256))
checksum_df.show(truncate=False)

print("\n 3. FILTRADO Y AGRUPACIÓN")
data = [("Ana", 25), ("Carlos", 30), ("Andrés", 22), ("Beatriz", 29)]
df = spark.createDataFrame(data, ["nombre", "edad"])
df_filtered = df.filter(col("nombre").startswith("A"))
df_filtered.show()

print("\n 4. ORDENACIÓN DISTRIBUIDA")
data = [(random.randint(1, 100),) for _ in range(10)]
df = spark.createDataFrame(data, ["numero"])
df_sorted = df.orderBy("numero")
df_sorted.show()

print(" 5. CÁLCULO DE MEDIA Y SUMA")
data = [(random.randint(1, 100),) for _ in range(10)]
df = spark.createDataFrame(data, ["valor"])
df_stats = df.select(avg("valor").alias("media"), sum("valor").alias("suma"))
df_stats.show()

print("\ 6. AGRUPACIÓN Y ESTADÍSTICAS")
data = [("A", random.randint(1, 100)) for _ in range(5)] + [("B", random.randint(1, 100)) for _ in range(5)]
df = spark.createDataFrame(data, ["grupo", "valor"])
df_grouped = df.groupBy("grupo").agg(
    count("valor").alias("conteo"),
    min("valor").alias("min"),
    max("valor").alias("max"),
    avg("valor").alias("media")
)
df_grouped.show()

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("MapReduceExample").getOrCreate()

rdd = spark.sparkContext.parallelize([
    "hola mundo", "hola Spark", "Spark es poderoso", "mundo de datos", "hola mundo"
])

rdd_map = rdd.flatMap(lambda line: line.split(" ")).map(lambda word: (word, 1))

print(rdd_map.collect())

rdd_reduce = rdd_map.reduceByKey(lambda a, b: a + b)

print(rdd_reduce.collect())

from pyspark.sql import SparkSession
from pyspark.sql import Row

spark = SparkSession.builder \
    .appName("Ejemplo PySpark SQL en Colab") \
    .getOrCreate()

datos = [
    Row(nombre="Alice", edad=29, ciudad="Madrid"),
    Row(nombre="Bob", edad=34, ciudad="Barcelona"),
    Row(nombre="Cathy", edad=29, ciudad="Madrid"),
    Row(nombre="David", edad=34, ciudad="Valencia"),
    Row(nombre="Eve", edad=29, ciudad="Madrid"),
]

df = spark.createDataFrame(datos)

df.createOrReplaceTempView("personas")

consulta_1 = spark.sql("SELECT * FROM personas WHERE ciudad = 'Madrid'")
print("Consulta 1: Personas en Madrid")
consulta_1.show()

consulta_2 = spark.sql("SELECT ciudad, COUNT(*) AS total_personas FROM personas GROUP BY ciudad")
print("Consulta 2: Conteo por ciudad")
consulta_2.show()

consulta_3 = spark.sql("SELECT AVG(edad) AS edad_promedio FROM personas")
print("Consulta 3: Edad promedio")
consulta_3.show()

consulta_4 = spark.sql("SELECT ciudad, COUNT(*) AS total FROM personas GROUP BY ciudad HAVING total > 1")
print("Consulta 4: Ciudades con más de una persona")
consulta_4.show()

from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, StringType, IntegerType

spark = SparkSession.builder.appName("SQL_Advanced_Examples").getOrCreate()

schema = StructType([
    StructField("name", StringType(), True),
    StructField("age", IntegerType(), True),
    StructField("city", StringType(), True),
    StructField("score", IntegerType(), True)
])

data = [
    ("Alice", 30, "New York", 85),
    ("Bob", 25, "Los Angeles", 75),
    ("Charlie", 35, "New York", 95),
    ("David", 40, "Chicago", 65),
    ("Eve", 29, "New York", 70),
    ("Frank", 30, "Chicago", 80),
    ("Grace", 22, "Los Angeles", 85)
]
df = spark.createDataFrame(data, schema=schema)

df.createOrReplaceTempView("people")

"""SELECT
    city,
    CASE
        WHEN age < 30 THEN 'Young'
        WHEN age >= 30 AND age < 40 THEN 'Mid-age'
        ELSE 'Older'
    END AS age_group,
    AVG(score) AS avg_score
FROM people
GROUP BY city, age_group

"""

result1 = spark.sql("""
SELECT
    city,
    CASE
        WHEN age < 30 THEN 'Young'
        WHEN age >= 30 AND age < 40 THEN 'Mid-age'
        ELSE 'Older'
    END AS age_group,
    AVG(score) AS avg_score
FROM people
GROUP BY city, age_group
""")
result1.show()

import matplotlib.pyplot as plt

from pyspark.sql import functions as F
city_counts = df.groupBy("city").count()
print(city_counts)
city_counts_pd = city_counts.toPandas()
print(city_counts_pd)

plt.figure(figsize=(10, 6))
plt.bar(city_counts_pd['city'], city_counts_pd['count'])
plt.xlabel("Ciudad")
plt.ylabel("Conteo")
plt.title("Número de personas por ciudad")
plt.show()