# -*- coding: utf-8 -*-
"""Modelos_Casas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vWU4C-fieDFtJrEDoFQTg8lkek61Go90

# Análisis de datos, procesamiento de datos y modelos de predicción
"""

import pandas as pd

df = pd.read_csv('/content/Real estate.csv')

df.head()

"""Visualizamos el dataset y sus respectivas columnas

"""

df.info()

df.describe()

"""CAMBIAMOS EL NOMBRE DE LAS COLUMNAS"""

df.rename(columns={
    "X1 transaction date": "Fecha_Transaccion",
    "X2 house age": "Edad_Casa",
    "X3 distance to the nearest MRT station": "Distancia_MRT",
    "X4 number of convenience stores": "Tiendas_Cercanas",
    "X5 latitude": "Latitud",
    "X6 longitude": "Longitud",
    "Y house price of unit area": "Precio_Unitario"
}, inplace=True)

df.head()

"""PERFILADO DE DATOS"""

!pip install ydata-profiling

from ydata_profiling import ProfileReport

profile = ProfileReport(df, explorative=True)

profile.to_notebook_iframe()

"""LIMPIEZA DEL DATASET"""

print(df.isnull().sum())

print(f"Filas duplicadas: {df.duplicated().sum()}")

df.dropna(inplace=True)

df.drop_duplicates(inplace=True)

print(df.isnull().sum())
print(f"Filas duplicadas: {df.duplicated().sum()}")

"""MATRIZ DE CORRELACIÓN"""

import matplotlib.pyplot as plt
import seaborn as sns


plt.figure(figsize=(10,6))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Matriz de Correlación")
plt.show()

"""VISUALIZAMOS EL DATASET"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6, 5))
sns.scatterplot(x=df["Distancia_MRT"], y=df["Precio_Unitario"], alpha=0.6)
plt.title("Distancia a MRT vs Precio Unitario")
plt.xlabel("Distancia a MRT (m)")
plt.ylabel("Precio Unitario")
plt.show()

plt.figure(figsize=(6, 5))
sns.boxplot(x=df["Tiendas_Cercanas"], y=df["Precio_Unitario"])
plt.title("Número de Tiendas Cercanas vs Precio Unitario")
plt.xlabel("Número de Tiendas Cercanas")
plt.ylabel("Precio Unitario")
plt.show()

plt.figure(figsize=(6, 5))
sns.scatterplot(x=df["Edad_Casa"], y=df["Precio_Unitario"], alpha=0.6, color="red")
plt.title("Edad de la Casa vs Precio Unitario")
plt.xlabel("Edad de la Casa (Años)")
plt.ylabel("Precio Unitario")
plt.show()

plt.figure(figsize=(6, 5))
sns.scatterplot(x=df["Longitud"], y=df["Latitud"], hue=df["Precio_Unitario"], palette="coolwarm")
plt.title("Mapa de Ubicaciones de Propiedades")
plt.xlabel("Longitud")
plt.ylabel("Latitud")
plt.show()

"""CREAMOS UN MAPA INTERACTIVO"""

import folium
from folium.plugins import MarkerCluster
import pandas as pd


mapa = folium.Map(location=[df["Latitud"].mean(), df["Longitud"].mean()], zoom_start=12)

marker_cluster = MarkerCluster().add_to(mapa)

for _, row in df.iterrows():
    folium.CircleMarker(
        location=[row["Latitud"], row["Longitud"]],
        radius=5,
        color="red" if row["Precio_Unitario"] > df["Precio_Unitario"].median() else "blue",
        fill=True,
        fill_color="red" if row["Precio_Unitario"] > df["Precio_Unitario"].median() else "blue",
        fill_opacity=0.6,
        popup=f"Precio: {row['Precio_Unitario']}"
    ).add_to(marker_cluster)

mapa

"""MODELOS

"""

from sklearn.model_selection import train_test_split

X = df.drop('Precio_Unitario', axis=1)
y = df['Precio_Unitario']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""REGRESIÓN LINEAL"""

from sklearn.linear_model import LinearRegression

modelo_rl = LinearRegression()
modelo_rl.fit(X_train, y_train)

y_pred_rl = modelo_rl.predict(X_test)

plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred_rl, alpha=0.6, color="blue", label="Predicciones")
plt.plot(y_test, y_test, color="red", linestyle="dashed", label="Línea Perfecta")
plt.xlabel("Valor Real de Precio Unitario")
plt.ylabel("Predicción del Modelo")
plt.title("Regresión Lineal: Predicciones vs Valores Reales")
plt.legend()
plt.show()

"""ÁRBOL DE DECISIONES"""

from sklearn.tree import DecisionTreeRegressor

modelo_ad = DecisionTreeRegressor(random_state=42)
modelo_ad.fit(X_train, y_train)

y_pred_ad = modelo_ad.predict(X_test)

from sklearn.tree import plot_tree

plt.figure(figsize=(20, 10))
plot_tree(modelo_ad, filled=True, feature_names=X_train.columns, max_depth=2)
plt.title("Estructura del Árbol de Decisión (Primeros 3 Niveles)")
plt.show()

"""RESULTADOS"""

from sklearn.metrics import mean_absolute_error, r2_score

mae_rl = mean_absolute_error(y_test, y_pred_rl)
r2_rl = r2_score(y_test, y_pred_rl)

mae_ad = mean_absolute_error(y_test, y_pred_ad)
r2_ad = r2_score(y_test, y_pred_ad)

print(f'Regresión Lineal - MAE: {mae_rl}, R²: {r2_rl}')
print(f'Árbol de Decisión - MAE: {mae_ad}, R²: {r2_ad}')

import matplotlib.pyplot as plt

modelos = ["Regresión Lineal", "Árbol de Decisión"]
mae = [mae_rl, mae_ad]
r2 = [r2_rl, r2_ad]

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

axes[0].bar(modelos, mae, color=["blue", "green"])
axes[0].set_title("Comparación de MAE (Error Absoluto Medio)")
axes[0].set_ylabel("MAE (Menor es Mejor)")

axes[1].bar(modelos, r2, color=["blue", "green"])
axes[1].set_title("Comparación de R² (Cuanto Más Cercano a 1, Mejor)")
axes[1].set_ylabel("R² Score")

plt.show()

from sklearn.ensemble import RandomForestRegressor

model_rf = RandomForestRegressor(n_estimators=100, random_state=42)
model_rf.fit(X_train, y_train)

y_pred_rf = model_rf.predict(X_test)

print("MAE:", mean_absolute_error(y_test, y_pred_rf))
print("R² Score:", r2_score(y_test, y_pred_rf))

plt.figure(figsize=(8, 6))
plt.scatter(y_test, model_rf.predict(X_test), alpha=0.6, color="green", label="Predicciones")
plt.plot(y_test, y_test, color="red", linestyle="dashed", label="Línea Perfecta")
plt.xlabel("Valor Real de Precio Unitario")
plt.ylabel("Predicción del Modelo")
plt.title("Random Forest: Predicciones vs Valores Reales")
plt.legend()
plt.show()

import joblib
import numpy as np

test_input = np.array([2012.917, 32, 1500, 8, 25.03, 121.54, 3.2]).reshape(1, -1)
print(f"Predicción del modelo: {model.predict(test_input)}")

import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

model_rf = RandomForestRegressor(n_estimators=100, random_state=42)
model_rf.fit(X_train, y_train)

y_pred_rf = model_rf.predict(X_test)

mae_rf = mean_absolute_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

modelos = ["Regresión Lineal", "Árbol de Decisión", "Random Forest"]
mae = [mae_rl, mae_ad, mae_rf]
r2 = [r2_rl, r2_ad, r2_rf]

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

axes[0].bar(modelos, mae, color=["blue", "green", "orange"])
axes[0].set_title("Comparación de MAE (Error Absoluto Medio)")
axes[0].set_ylabel("MAE (Menor es Mejor)")

axes[1].bar(modelos, r2, color=["blue", "green", "orange"])
axes[1].set_title("Comparación de R² (Cuanto Más Cercano a 1, Mejor)")
axes[1].set_ylabel("R² Score")

plt.show()

import joblib

joblib.dump(model_rf, "modelo_rf.pkl")

from google.colab import files
files.download("modelo_rf.pkl")